title : John Bohn
tagline: ~
author :
  name : John Bohn
  email : jjbohn@gmail.com
  github : jjbohn
  twitter : jjbohn
  feedburner : ~

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md

